import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { SMTPClient } from 'emailjs';
import axios from 'axios';

import { NextApiRequest, NextApiResponse } from 'next';
import {AxiosResponse} from 'axios';
 
export default function SchoolMangement() {
 
 const [email,setEmail]=useState('')
//  const SendMail = async (e: any)=>{
//    e.preventDefault();
// console.log('call')
// console.log("emmhjkll", email)

// await axios.post('http://localhost:3000/api/users/email',{email})
//    .then((res: any)=>{
//     console.log(res,"++++++++++++")
//      alert('Send Mail To You')
//      setEmail('')
 
//    }).catch(
//      (e: any)=>console.log(e)
//    )
//  }
 
 
 const  sendMail = (req: NextApiRequest, res: NextApiResponse) =>  {
 
 const {email}=req.body;
 // console.log(process.env)
 axios.post('http://localhost:3000/api/email',{email})
   .then(
    
   (res: AxiosResponse)=>{
     alert('Send Mail To You')
     setEmail('')
 
   }
 
   ).catch(
     (e)=>console.log(e)
   )
 
 
 
 try{
 
  const client = new SMTPClient({
    user: process.env.mail,
    password: process.env.password,
    host: 'vidyavathi15@gmail.com',
    ssl:true
  });
  
  //  client.send({
  //      text: `Just for testing purpose`,
  //      from: process.env.NEXT_PUBLIC_MAIL as any,
  //      to: email,
  //      subject: 'testing emailjs',
      
  //    }
  //    )
   }
 catch(e){
   res.status(400).end(JSON.stringify({ message:"Error" }))
   return;
 }
 
 res.status(200).end(JSON.stringify({ message:'Send Mail' }))
}
 
 return (
   <div className={styles.container}>
     <Head>
       <title>Create Next App</title>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/favicon.ico" />
     </Head>
    
 
     <main className={styles.main}>
       <form>
      <input type="email" placeholder="Enter Mail" required value={email} onChange={(e)=>setEmail(e.target.value)}></input>
      {/* <button type="button" onClick={()=>sendMail()}>Send</button> */}
        </form>
     </main>
   </div>
 )
}
